### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by eghernqvist** [keymetrics/pm2-io-apm#209]
## Expected Behavior
Custom metric should work and increase via `metric.mark()` as per docs.

## Actual Behavior
Throws `TypeError: printPerSec.mark is not a function`

### 1. Initialize `@pm2/io`:
```javascript
  const io = require('@pm2/io');
  io.init({
    metrics: {
      network: {
        traffic: false,
      },
    }
  })
```
  ### 2. Create custom metric:
```javascript
  const printPerSec = io.metric({
    name: 'prints/sec',
    type: 'meter',
  });
```
  ### 3. Run `printPerSec.mark()`:
```javascript
  printPerSec.mark();
  > TypeError: printPerSec.mark is not a function
```

## Specifications

  - PM2 version: 3.2.2
  - Node version: 8.11.4

**Comment by vmarchaud** [comment]
While we fix this bug (might take some times), you can declare a meter like that : 
```
const msgBySec = pmx.meter({
  name: 'msg/sec',
  samples: 1,
  timeframe: 60
})
```

(You should keep the samples & timeframe to their default)

**Comment by vmarchaud** [comment]
Both should be working with the newest version (3.0.0)
