### ISSUE TITLE
Version 2.3.6 Throws getInitialConfig is not a function

### ISSUE THREAD

**Issue by mdw19873** [keymetrics/pm2-io-apm#188]
After updating to 2.3.6, my application now throws the following error:

> global[IO_KEY].getInitialConfig is not a function

Reverting to 2.3.2 corrects the issues.
I'm running Node 8 on CentOS 7 installed via NPM

Please let me know what else you need

**Comment by wallet77** [comment]
Hi @mdw19873 

Will be fixed in next release, coming soon.

**Comment by wallet77** [comment]
Fixed in 2.3.11
